[tool.poetry]
name = "homework-web-2"
version = "0.1.0"
description = ""
authors = ["Viktoria-I <viktoria@nitra.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
